name: SEIDO OCR CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go 1.24
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'
        cache: true

    - name: Install Dependencies
      run: go mod download

    - name: Verify Module
      run: go mod verify

    - name: Build API Service
      # Memastikan folder cmd/api tidak error
      run: go build -v -o seido-api ./cmd/api/...

    - name: Build OCR Worker
      # Memastikan folder cmd/ocr-worker tidak error
      run: go build -v -o seido-worker ./cmd/ocr-worker/...

    - name: Run Unit Tests
      # Menjalankan semua test di internal dan pkg
      run: go test -v ./internal/... ./pkg/...